CREATE DATABASE IF NOT EXISTS selfmusic;

USE selfmusic;

CREATE TABLE IF NOT EXISTS users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(20) UNIQUE NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS music (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    artist VARCHAR(100) NOT NULL,
    type VARCHAR(20),
    filename VARCHAR(255) UNIQUE NOT NULL,
    image LONGTEXT,
);
