CREATE DATABASE IF NOT EXISTS selfmusic;

USE selfmusic;

CREATE TABLE IF NOT EXISTS music (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    artist VARCHAR(100) NOT NULL,
    type VARCHAR(20),
    filename VARCHAR(255) UNIQUE NOT NULL,
    image LONGTEXT,
);
